"""
Django settings for fruitsite project.

Generated by 'django-admin startproject' using Django 5.2.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""



from pathlib import Path
import os
from dotenv import load_dotenv

import dj_database_url

# Загружаем переменные из .env файла
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Используем DATABASE_URL из .env файла
DATABASE_URL = os.environ.get('DATABASE_URL', 'postgres://postgres:qkTkjkQANVmhNfzdBbUvFETYxfUSltFO@tramway.proxy.rlwy.net:58115/railway')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/


# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY', 'django-insecure-...')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# Получаем ALLOWED_HOSTS из переменной окружения и добавляем localhost для разработки
allowed_hosts_env = os.environ.get('ALLOWED_HOSTS', '')
ALLOWED_HOSTS = [host.strip() for host in allowed_hosts_env.split(',') if host.strip()] if allowed_hosts_env else []

# Добавляем localhost для разработки, если DEBUG=True
if DEBUG:
    development_hosts = ['127.0.0.1', 'localhost', '127.0.0.1:8000', 'localhost:8000']
    for host in development_hosts:
        if host not in ALLOWED_HOSTS:
            ALLOWED_HOSTS.append(host)

# В settings.py
CSRF_TRUSTED_ORIGINS = [
    'http://localhost:8000',
    'http://127.0.0.1:8000'
]

# Дополнительные настройки CSRF для разработки
CSRF_COOKIE_SECURE = False  # Для HTTP в разработке
CSRF_COOKIE_HTTPONLY = False
CSRF_USE_SESSIONS = False
CSRF_COOKIE_SAMESITE = 'Lax'

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'allauth.account.middleware.AccountMiddleware',
]

ROOT_URLCONF = 'fruitsite.urls'


TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'fruitsite', 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.csrf',
                'products.context_processors.categories',
            ],
        },
    },
]


ASGI_APPLICATION = 'fruitsite.asgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

INSTALLED_APPS = [
    # Django defaults
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Локальные приложения
    'storages',
    'accounts',
    'widget_tweaks',
    'products',
    'cart',
    'orders',
    'chat',
    'reviews',

    # Сторонние приложения
    'tailwind',
    'theme',
    'django_browser_reload',
    'channels',
    'pwa',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    
]




TAILWIND_APP_NAME = 'theme'



DATABASES = {
    'default': dj_database_url.parse(DATABASE_URL, conn_max_age=600)
}



# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'theme', 'static'),
]
STATIC_URL = '/static/'

# Все собранные файлы будут сюда
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# Папка исходников статики (Tailwind и прочее)
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'theme', 'static'),
]

# ⚡ Включи WhiteNoise для продакшн
MIDDLEWARE.insert(1, 'whitenoise.middleware.WhiteNoiseMiddleware')

STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'



# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

AUTH_USER_MODEL = 'accounts.User'

NPM_BIN_PATH = "C:/Program Files/nodejs/npm.cmd"

# При локальной разработке и тестировании используем локальные медиа-файлы
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# CSRF trusted origins for Railway production
CSRF_TRUSTED_ORIGINS = os.environ.get('CSRF_TRUSTED_ORIGINS', 'https://fruitsite-production.up.railway.app').split(',')


# Настройки S3 Selectel
AWS_ACCESS_KEY_ID = '415fa12c022c42a7b5f6ed4d7f59e5e5'  # Из панели Selectel
AWS_SECRET_ACCESS_KEY = 'deffb7f08ac845799c1eca153a96cab2'  # Из панели Selectel
AWS_STORAGE_BUCKET_NAME = 'fruitsite'  # Имя созданного бакета
AWS_S3_ENDPOINT_URL = 'https://s3.storage.selcloud.ru'  # Endpoint Selectel
AWS_S3_REGION_NAME = 'ru-1'  # Или другой регион, если у вас не ru-1
AWS_S3_SIGNATURE_VERSION = 's3v4'
AWS_DEFAULT_ACL = 'public-read'  # Все файлы публичные для доступа без авторизации
AWS_QUERYSTRING_AUTH = False  # Отключаем query-параметры авторизации для чистых URL

# Дополнительные настройки для работы с URL
AWS_S3_CUSTOM_DOMAIN = None  # Не используем кастомный домен для корректной работы Selectel
AWS_S3_URL_PROTOCOL = 'https'  # Явно указываем протокол https

# Прямой URL Selectel (полученный из примера URL)
SELECTEL_DIRECT_STORAGE_URL = 'https://8b0b75a0-d659-4da7-ae25-c18735213846.selstorage.ru'

# Дополнительные настройки для стабильной работы с S3
AWS_S3_ADDRESSING_STYLE = 'path'  # Использование path-стиля адресации для Selectel S3
AWS_S3_VERIFY = True  # Проверять SSL-сертификаты
AWS_S3_SECURE_URLS = True  # Использовать HTTPS
AWS_S3_USE_SSL = True  # Использовать SSL для подключения
AWS_S3_MAX_MEMORY_SIZE = 5 * 1024 * 1024  # 5 MB - оптимальный размер для загрузки
AWS_S3_FILE_OVERWRITE = False  # Не перезаписывать файлы с одинаковыми именами

# Таймауты для S3
AWS_S3_CONNECT_TIMEOUT = 60  # 60 секунд на установление соединения
AWS_S3_READ_TIMEOUT = 60  # 60 секунд на чтение данных

# Настройки хранения файлов
DEFAULT_FILE_STORAGE = 'fruitsite.storage_backends.MediaStorage'