# Generated by Django 5.2.3 on 2025-07-12 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='unit_type',
            field=models.CharField(choices=[('unit', 'За единицу'), ('package', 'За упаковку')], default='unit', max_length=10, verbose_name='Тип единицы'),
        ),
    ]
