# Generated by Django 5.2.3 on 2025-07-10 17:56

import django.db.models.deletion
import fruitsite.storage_backends
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование продукции')),
                ('description', models.TextField()),
                ('volume', models.CharField(blank=True, default='', max_length=50, verbose_name='Объем, г')),
                ('package_type', models.CharField(blank=True, default='', max_length=100, verbose_name='Вид упаковки')),
                ('quantity_in_package', models.PositiveIntegerField(default=1, verbose_name='Количество в упаковке')),
                ('price_per_unit', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Цена за единицу')),
                ('price_per_package', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Цена за упаковку')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('old_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Старая цена')),
                ('stock', models.PositiveIntegerField(default=1)),
                ('sizes', models.CharField(blank=True, help_text='Выберите один или несколько размеров через запятую (например: S,M,L)', max_length=100, verbose_name='Доступные размеры')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.category')),
                ('master', models.ForeignKey(limit_choices_to={'role': 'master'}, on_delete=django.db.models.deletion.CASCADE, related_name='products', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(storage=fruitsite.storage_backends.ProductImagesStorage(), upload_to='product_images/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.product')),
            ],
        ),
    ]
