# Generated by Django 5.2.3 on 2025-07-12 12:00

from django.db import migrations, models
import fruitsite.storage_backends


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_remove_product_sizes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(storage=fruitsite.storage_backends.ProductImagesStorage(), upload_to='product_images/'),
        ),
    ]