# Generated by Django 5.2.3 on 2025-07-12 12:45

from django.db import migrations

def make_existing_categories_global(apps, schema_editor):
    Category = apps.get_model('products', 'Category')
    # Устанавливаем все существующие категории как глобальные
    Category.objects.filter(created_by__isnull=True).update(is_global=True)

def reverse_make_existing_categories_global(apps, schema_editor):
    Category = apps.get_model('products', 'Category')
    # Откатываем изменения - убираем флаг глобальности
    Category.objects.filter(created_by__isnull=True).update(is_global=False)

class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_category_created_by_category_is_global_and_more'),
    ]

    operations = [
        migrations.RunPython(
            make_existing_categories_global,
            reverse_make_existing_categories_global
        ),
    ]
